// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_U2UosIb2aWfJ4SS7mBw5bjdC_PKrw4A',
    appId: '1:277231424099:web:7d2718f343407f60091e56',
    messagingSenderId: '277231424099',
    projectId: 'urbanculture-e3963',
    authDomain: 'urbanculture-e3963.firebaseapp.com',
    storageBucket: 'urbanculture-e3963.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6g9EP1nDAwYD96DEt43tWwKwHR9YHcw',
    appId: '1:277231424099:android:f101f3cd1a095b2f091e56',
    messagingSenderId: '277231424099',
    projectId: 'urbanculture-e3963',
    storageBucket: 'urbanculture-e3963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8shf9YgGJvxBA9IawCHitKp-dAX5BRc',
    appId: '1:277231424099:ios:135e028c6ac6d449091e56',
    messagingSenderId: '277231424099',
    projectId: 'urbanculture-e3963',
    storageBucket: 'urbanculture-e3963.appspot.com',
    iosBundleId: 'com.example.urbanculture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk8shf9YgGJvxBA9IawCHitKp-dAX5BRc',
    appId: '1:277231424099:ios:135e028c6ac6d449091e56',
    messagingSenderId: '277231424099',
    projectId: 'urbanculture-e3963',
    storageBucket: 'urbanculture-e3963.appspot.com',
    iosBundleId: 'com.example.urbanculture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_U2UosIb2aWfJ4SS7mBw5bjdC_PKrw4A',
    appId: '1:277231424099:web:994d38297ef5383a091e56',
    messagingSenderId: '277231424099',
    projectId: 'urbanculture-e3963',
    authDomain: 'urbanculture-e3963.firebaseapp.com',
    storageBucket: 'urbanculture-e3963.appspot.com',
  );
}
